"""M1: build reports/data_card.md from results/m1_data_audit.json and results/m1_tokenizer_stats.json.

Usage:
    uv run python scripts/m1_data_card.py
"""
import json

from bangla_sentiment.utils import ROOT, RESULTS_DIR


def load(name):
    return json.loads((RESULTS_DIR / f"{name}.json").read_text(encoding="utf-8"))


def table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def pct(part, whole):
    return f"{part} ({100 * part / whole:.1f}%)"


def dataset_section(name, a):
    splits = ["train", "val", "test"]
    labels = sorted(a["class_counts"]["train"])
    d = a["duplicates"]
    out = [f"## {name}", ""]
    out += [f"- Source: `{a['source']['repo_id']}` at revision `{a['source']['revision'][:12]}`",
            f"- License: {a['license']}",
            f"- Label mapping (raw to name): {a['label_mapping']['raw_to_name']}. "
            f"Matches the published class counts: **{a['label_mapping']['matches_published']}** "
            f"({a['label_mapping']['observed_counts']})", ""]
    out += ["### Rows and classes", ""]
    rows = []
    for s in splits:
        n = a["rows_final"][s]
        rows.append([s, a["rows_raw"][s], n] + [pct(a["class_counts"][s].get(lab, 0), n) for lab in labels])
    out += [table(["split", "rows (raw)", "rows (final)"] + labels, rows), ""]
    out += ["### Text length (normalized text)", ""]
    rows = [[s] + [a["words_per_text"][s][k] for k in ("mean", "median", "p95", "p99", "max")]
            + [a["chars_per_text"][s]["median"], a["normalizer_changed_share"][s]] for s in splits]
    out += [table(["split", "words mean", "median", "p95", "p99", "max", "chars median", "changed by normalizer"],
                  rows), ""]
    out += ["### Duplicates and leakage", ""]
    rows = []
    for kind in ("exact", "near"):
        k = d[kind]
        rows.append([kind] + [k["extra_copies_within_split"][s] for s in splits]
                    + [k["cross_split"][c] for c in ("train_rows_also_in_val", "train_rows_also_in_test",
                                                     "val_rows_also_in_test")]
                    + [k["train_duplicate_groups_with_conflicting_labels"]])
    out += [table(["match", "extra copies in train", "in val", "in test", "train rows in val", "train rows in test",
                   "val rows in test", "train groups with conflicting labels"], rows), ""]
    out += [f"Near duplicates ignore punctuation, digits, spacing and emoji. "
            f"**{a['dropped_from_train_for_leakage']}** train rows that near-duplicate a val or test row were "
            f"removed from train. Val and test are unchanged, so published numbers stay comparable. "
            f"Texts without any letters: {d['texts_without_letters']}.", ""]
    out += ["### Training subsets (seed 0, nested and stratified)", ""]
    rows = [[n] + [c.get(lab, 0) for lab in labels] for n, c in a["subset_class_counts_seed_0"].items()]
    out += [table(["size"] + labels, rows), ""]
    return out


def tokenizer_section(tok, dataset):
    rows = []
    for key, v in tok.items():
        s = v[dataset]
        t = s["tokens_per_text"]
        rows.append([key, s["vocab_size"], s["tokens_per_word"], s["tokens_per_char"], t["median"], t["p95"],
                     t["p99"], t["max"], s["share_over_128_tokens"], s["unk_rate"], s["byte_fallback_rate"]])
    return [table(["tokenizer", "vocab", "tokens/word", "tokens/char", "median tokens", "p95", "p99", "max",
                   "share > 128", "unk rate", "byte fallback"], rows), ""]


def main():
    audit, tok = load("m1_data_audit"), load("m1_tokenizer_stats")
    out = ["# Data card", "",
           "Generated by `scripts/m1_data_card.py` from `results/m1_data_audit.json` "
           f"(commit `{audit['meta']['git_commit']}`) and `results/m1_tokenizer_stats.json` "
           f"(commit `{tok['meta']['git_commit']}`). Do not edit by hand.", "",
           "All text is normalized with the BanglaBERT normalizer and whitespace collapsing, the same "
           "pipeline for every model. No dataset text is stored in this repository.", ""]
    for name, a in audit["datasets"].items():
        out += dataset_section(name, a)
        out += [f"### Tokenizer cost on {name} train (A1, text only, no prompt)", ""]
        out += tokenizer_section(tok["tokenizers"], name)
    path = ROOT / "reports" / "data_card.md"
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
